### ISSUE TITLE
Not able to deploy  EnterpriseAWSSSOPipelineStack 

### ISSUE THREAD

**Issue by agaur5-gild** [aws-samples/assignment-automation-4-aws-sso#18]
Hi team, i am trying to run this command `cdk deploy EnterpriseAWSSSOPipelineStack ` but this shows error.
Attaching screenshot here.
<img width="1134" alt="image" src="https://github.com/aws-samples/assignment-automation-4-aws-sso/assets/118471339/f4eb4c86-044c-49e8-a0cc-6dc2283cec42">

**Comment by ivan-aws** [comment]
apologies, this was missed.

the error is happening because `cdk.json` has been updated to point to `app.py` instead of `cdkpipelines_app.py`. this mistake is now fixed and will soon be merged back into the main branch

**Comment by ivan-aws** [comment]
fix has been merged.
